import Head from 'next/head';
import React from 'react';
import {
	Image,
	Button,
	Heading,
	useBreakpointValue,
	Flex,
	Center,
	VStack,
} from '@chakra-ui/react';
import { colors } from '@/theme/theme';
import { SplashPageFooter } from '@/components/layout/SplashPageFooter';
import { useRouter } from 'next/router';

export default function Home() {
	const router = useRouter();
	const isMobile = useBreakpointValue({ base: true, sm: true, md: false });

	return (
		<>
			<Head>
				<title>{"Sammy's Sandwiches"}</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Flex
				h={isMobile ? 'auto' : '90vh'}
				direction={['column', 'column', 'row']}
				justifyContent={isMobile ? 'space-between' : ''}
			>
				<Center px={5} w={isMobile ? '100vw' : '50vw'}>
					<Image
						rounded={'md'}
						h={'80%'}
						fit="cover"
						alt="sandwich"
						src="2sandiwches.jpg"
						boxShadow="dark-lg"
					/>
				</Center>
				<Center px={5} w={isMobile ? '100vw' : '50vw'}>
					<VStack p={5} rounded="md">
						<Heading
							textAlign="center"
							size={['lg']}
							color={colors.black}
						>
							{"Click to begin ordering a Sammy's Sandwich"}
						</Heading>
						<Button
							onClick={() => router.push('/order')}
							size={'lg'}
						>
							Order
						</Button>
					</VStack>
				</Center>
			</Flex>
		</>
	);
}
